# numbers_test.py: test numbers FSM

class NumberTest():
    def run(self, test, debug, numberMachine):
        allTests = test == 0
        if test == 1 or allTests:
            print("1. Zero and simple decimals:")
            numberMachine.runAndReport("0", debug)
            numberMachine.runAndReport("5", debug)
            numberMachine.runAndReport("19", debug)
            numberMachine.runAndReport("1a", debug)
            numberMachine.runAndReport("h", debug)
            numberMachine.runAndReport("234567890", debug)
            numberMachine.runAndReport("456070801042345", debug)
            numberMachine.runAndReport("-1", debug)
        if test == 2 or allTests:
            print("2. octals:")
            numberMachine.runAndReport("05", debug)
            numberMachine.runAndReport("07", debug)
            numberMachine.runAndReport("08", debug)
            numberMachine.runAndReport("082", debug)
            numberMachine.runAndReport("00", debug)
            numberMachine.runAndReport("064531003425", debug)
            numberMachine.runAndReport("020x443", debug)
            numberMachine.runAndReport("034.53", debug)
            numberMachine.runAndReport("04c5", debug)
            numberMachine.runAndReport("0000", debug)
            numberMachine.runAndReport("018", debug)
            numberMachine.runAndReport("00x5", debug)
            numberMachine.runAndReport("01324?54", debug)
            numberMachine.runAndReport("007", debug)
            numberMachine.runAndReport("008", debug)
        if test == 3 or allTests:
            print("3. hexadecimals:")
            numberMachine.runAndReport("0x9", debug)
            numberMachine.runAndReport("0xfedcba0123456789", debug)
            numberMachine.runAndReport("0xABCDEF", debug)
            numberMachine.runAndReport("0x0a1BccEF9873", debug)
            numberMachine.runAndReport("0x3x5", debug)
            numberMachine.runAndReport("0x40x8", debug)
            numberMachine.runAndReport("0xb", debug)
            numberMachine.runAndReport("0x1.2", debug)
            numberMachine.runAndReport("0xcde120x532", debug)
            numberMachine.runAndReport("0x0", debug)
            numberMachine.runAndReport("0x00", debug)
        if test == 4 or allTests:
            print("4. floats:")
            numberMachine.runAndReport("1.234567890", debug)
            numberMachine.runAndReport("20324231243.234567890", debug)
            numberMachine.runAndReport("413.23e5", debug)
            numberMachine.runAndReport("596.4.5.342", debug)
            numberMachine.runAndReport("698765.0", debug)
            numberMachine.runAndReport("-2344.23", debug)
            numberMachine.runAndReport(".4561230234", debug)
            numberMachine.runAndReport(".0456789012345", debug)
            numberMachine.runAndReport(".", debug)
            numberMachine.runAndReport("777.a95", debug)
            numberMachine.runAndReport("20324231243.234567890", debug)
            numberMachine.runAndReport("8.", debug)
            numberMachine.runAndReport(".8", debug)
